server:
  port: 8081
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/ddd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:ddd}
    password: ${DB_PASSWORD:dddpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.example: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
metrics:
  logging:
    interval: 10000
